### ISSUE TITLE
Update NPM package with latest changes

### ISSUE THREAD

**Issue by T0T4R4** [tobiassoltermann/node-red-contrib-powershell#7]
It looks like the latest changes haven't been reflected on NPM. 

Would it be possible for you to trigger a new deployment to npm ?

Thanks :)

**Comment by T0T4R4** [comment]
Are you using github actions ?
Maybe I could do it if you don't have the time :)

**Comment by tobiassoltermann** [comment]
My apologies, I do not have too much time for this at the moment. I've
invited you to the repo, please feel free to do whatever you wish. :-)

Am So., 21. Feb. 2021 um 23:13 Uhr schrieb T0t4r4 <notifications@github.com

**Comment by T0T4R4** [comment]
Thank you very much ! Will do !

Regards
Mat

**Comment by T0T4R4** [comment]
@tobiassoltermann what process did you follow to publish to NPM ? 
Is there a way you could give me the access to 
https://www.npmjs.com/package/node-red-contrib-powershell

**Comment by RainerGa** [comment]
Hello @T0T4R4 ,

it would be great if you update the npm package :-)

Thank you!
Rainer

**Comment by T0T4R4** [comment]
Hi @RainerGa,

I'll see what I can do,

Regards
