### ISSUE TITLE
Output not in msg.payload

### ISSUE THREAD

**Issue by sniicker** [tobiassoltermann/node-red-contrib-powershell#8]
Hi,

the output of your node is in msg instead of msg.payload.

Can you change this or can you tell me a way how to move it there? 

I tried it with a change and a function node but failed.

Thx

**Comment by HaroldPetersInskipp** [comment]
A function node containing:
<code>return {payload: msg};</code>
placed after the powershell node will work

**Comment by sniicker** [comment]
Thanks.
